In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

In [2]:
data = pd.read_csv('./data/creaditcard_fraud_data.csv')
data

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,Luray,...,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
1852390,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,Lake Jackson,...,29.0393,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
1852391,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,Burbank,...,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
1852392,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,Mesa,...,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
1852393,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,Edmond,...,35.6665,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

In [3]:
# 데이터 타입 확인
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1852394 entries, 0 to 1852393
Data columns (total 22 columns):
 #   Column                 Dtype
---  ------                 -----
 0   trans_date_trans_time  object
 1   cc_num                 int64
 2   merchant               object
 3   category               object
 4   amt                    float64
 5   first                  object
 6   last                   object
 7   gender                 object
 8   street                 object
 9   city                   object
 10  state                  object
 11  zip                    int64
 12  lat                    float64
 13  long                   float64
 14  city_pop               int64
 15  job                    object
 16  dob                    object
 17  trans_num              object
 18  unix_time              int64
 19  merch_lat              float64
 20  merch_long             float64
 21  is_fraud               int64
dtypes: float64(5), int64(5), object(12)
memory usage: 310.9+ MB

In [4]:
data = data.drop(['first', 'last', 'street', 'city', 'state', 'zip', 'trans_num', 'unix_time'], axis = 1)
data

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,M,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,46.2306,-112.1138,1939,Patent attorney,1967-01-12,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,M,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,M,40.4931,-91.8912,519,Town planner,1966-02-13,39.946837,-91.333331,0
1852390,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,M,29.0393,-95.4401,28739,Futures trader,1999-12-27,29.661049,-96.186633,0
1852391,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,F,46.1966,-118.9017,3684,Musician,1981-11-29,46.658340,-119.715054,0
1852392,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,M,44.6255,-116.4493,129,Cartographer,1965-12-15,44.470525,-117.080888,0
1852393,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,M,35.6665,-97.4798,116001,Media buyer,1993-05-10,36.210097,-97.036372,0

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
train, test = train_test_split(data, stratify = data['is_fraud'], test_size = 0.4, random_state = 7)
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud
818498,2019-12-08 14:27:05,4292902571056973207,"fraud_Turner, Ruecker and Parisian",misc_pos,36.38,M,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,46.500378,-113.166539,0
368569,2019-06-20 00:44:00,5152054598359927,"fraud_Lockman, West and Runte",grocery_pos,36.45,M,29.8872,-90.0331,55581,Biomedical scientist,1972-09-12,30.229110,-89.380019,0
1190082,2020-05-12 01:26:40,3547574373318979,"fraud_Huel, Hammes and Witting",grocery_pos,123.05,M,39.0319,-88.4074,2092,"Psychologist, clinical",1962-04-30,38.558958,-88.122956,0
1295688,2020-06-21 03:37:16,213157767990030,fraud_Wisozk and Sons,misc_pos,151.77,F,41.6060,-109.2300,27971,Music therapist,1984-08-01,42.121831,-109.861563,0
1465988,2020-08-19 05:20:56,4426075337087318654,"fraud_Herman, Treutel and Dickens",misc_net,1.75,M,39.0645,-95.6413,163415,Clinical cytogeneticist,1975-06-25,38.269669,-95.651064,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2678,2019-01-02 07:04:23,3517527805128735,fraud_Bednar Group,misc_net,785.98,F,41.1573,-88.0619,1617,Medical secretary,1990-04-25,40.242491,-88.113635,0
609589,2019-09-15 23:15:47,36485887555770,fraud_Shields-Wunsch,health_fitness,1.57,M,40.4971,-82.8342,267,Facilities manager,2005-01-29,41.349713,-82.224897,0
1534209,2020-09-14 22:42:04,38947654498698,"fraud_Herman, Treutel and Dickens",misc_net,314.33,F,39.3543,-82.5030,321,"Copywriter, advertising",1979-06-24,38.636519,-83.206128,0
1170682,2020-05-03 23:14:48,4189814094741,fraud_Schumm PLC,health_fitness,1.17,M,33.7367,-86.1619,4159,Educational psychologist,1998-02-03,33.290748,-86.806002,0
909107,2019-12-28 22:26:35,2269768987945882,"fraud_Hettinger, McCullough and Fay",home,33.23,F,42.6835,-77.8664,4895,Acupuncturist,1958-10-29,42.558121,-78.691432,0

# 카드 번호에 따른 평균 지출액, 표준편차 구하기

In [7]:
train.groupby('cc_num')['amt'].agg(['mean', 'std']).reset_index()

                  cc_num        mean          std
0            60416207185   56.289152   131.019313
1            60422928733   63.614413    91.792484
2            60423098130  124.571670  1299.417508
3            60427851591  105.873482   133.498858
4            60487002085   70.717074   184.148074
..                   ...         ...          ...
994  4958589671582726883   70.863361   159.727682
995  4973530368125489546   80.548145   322.265476
996  4980323467523543940   71.742605   128.351949
997  4989847570577635369   94.196511   134.027279
998  4992346398065154184   68.992091   156.613459

[999 rows x 3 columns]

In [8]:
amt_by_cc_num =  train.groupby('cc_num')['amt'].agg(['mean', 'std']).reset_index()
amt_by_cc_num

                  cc_num        mean          std
0            60416207185   56.289152   131.019313
1            60422928733   63.614413    91.792484
2            60423098130  124.571670  1299.417508
3            60427851591  105.873482   133.498858
4            60487002085   70.717074   184.148074
..                   ...         ...          ...
994  4958589671582726883   70.863361   159.727682
995  4973530368125489546   80.548145   322.265476
996  4980323467523543940   71.742605   128.351949
997  4989847570577635369   94.196511   134.027279
998  4992346398065154184   68.992091   156.613459

[999 rows x 3 columns]

In [9]:
train = pd.merge(train, amt_by_cc_num, how = 'left', on = 'cc_num')
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,mean,std
0,2019-12-08 14:27:05,4292902571056973207,"fraud_Turner, Ruecker and Parisian",misc_pos,36.38,M,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,46.500378,-113.166539,0,68.647641,65.068697
1,2019-06-20 00:44:00,5152054598359927,"fraud_Lockman, West and Runte",grocery_pos,36.45,M,29.8872,-90.0331,55581,Biomedical scientist,1972-09-12,30.229110,-89.380019,0,61.405718,157.527222
2,2020-05-12 01:26:40,3547574373318979,"fraud_Huel, Hammes and Witting",grocery_pos,123.05,M,39.0319,-88.4074,2092,"Psychologist, clinical",1962-04-30,38.558958,-88.122956,0,63.552445,111.500902
3,2020-06-21 03:37:16,213157767990030,fraud_Wisozk and Sons,misc_pos,151.77,F,41.6060,-109.2300,27971,Music therapist,1984-08-01,42.121831,-109.861563,0,95.250834,152.024640
4,2020-08-19 05:20:56,4426075337087318654,"fraud_Herman, Treutel and Dickens",misc_net,1.75,M,39.0645,-95.6413,163415,Clinical cytogeneticist,1975-06-25,38.269669,-95.651064,0,58.805353,97.932683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2019-01-02 07:04:23,3517527805128735,fraud_Bednar Group,misc_net,785.98,F,41.1573,-88.0619,1617,Medical secretary,1990-04-25,40.242491,-88.113635,0,56.089428,125.073033
1111432,2019-09-15 23:15:47,36485887555770,fraud_Shields-Wunsch,health_fitness,1.57,M,40.4971,-82.8342,267,Facilities manager,2005-01-29,41.349713,-82.224897,0,70.520312,73.261695
1111433,2020-09-14 22:42:04,38947654498698,"fraud_Herman, Treutel and Dickens",misc_net,314.33,F,39.3543,-82.5030,321,"Copywriter, advertising",1979-06-24,38.636519,-83.206128,0,53.651696,109.722256
1111434,2020-05-03 23:14:48,4189814094741,fraud_Schumm PLC,health_fitness,1.17,M,33.7367,-86.1619,4159,Educational psychologist,1998-02-03,33.290748,-86.806002,0,57.839833,154.121481
1111435,2019-12-28 22:26:35,2269768987945882,"fraud_Hettinger, McCullough and Fay",home,33.23,F,42.6835,-77.8664,4895,Acupuncturist,1958-10-29,42.558121,-78.691432,0,65.545907,101.467606

# 이상지출 탐지하기
- 평소 사용자가 지출하던 금액보다 과도하게 높은 경우
- z 스코어를 이용해 탐지
- z 스코어 : 값 - 평균 / 표준편차

In [10]:
train['amt_z_score'] = (train['amt'] - train['mean']) / train['std']

In [11]:
train[['amt', 'mean', 'std', 'amt_z_score']]

            amt       mean         std  amt_z_score
0         36.38  68.647641   65.068697    -0.495901
1         36.45  61.405718  157.527222    -0.158422
2        123.05  63.552445  111.500902     0.533606
3        151.77  95.250834  152.024640     0.371776
4          1.75  58.805353   97.932683    -0.582598
...         ...        ...         ...          ...
1111431  785.98  56.089428  125.073033     5.835715
1111432    1.57  70.520312   73.261695    -0.941151
1111433  314.33  53.651696  109.722256     2.375802
1111434    1.17  57.839833  154.121481    -0.367696
1111435   33.23  65.545907  101.467606    -0.318485

[1111436 rows x 4 columns]

In [12]:
train[train['amt_z_score'] > 3]

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,mean,std,amt_z_score
46,2020-04-27 22:11:48,639046421587,"fraud_Hahn, Douglas and Schowalter",travel,487.93,M,40.5662,-80.2099,1140,"Administrator, education",1986-06-20,40.659444,-80.655374,0,100.767825,111.819680,3.462380
159,2019-07-14 16:44:53,30273037698427,"fraud_Jones, Sawayn and Romaguera",misc_net,333.78,M,35.5762,-91.4539,111,Careers information officer,2000-06-13,35.178202,-90.980453,0,72.643530,79.724988,3.275466
222,2019-11-30 17:21:09,213191402330021,fraud_Fisher Inc,shopping_net,646.46,M,42.9676,-88.0434,817312,"Accountant, chartered public finance",2004-03-18,42.336308,-88.049694,0,46.248314,100.545048,5.969580
263,2020-11-24 06:45:27,340953839692349,fraud_Block-Parisian,misc_net,1308.81,M,42.5164,-82.9832,134056,"Doctor, hospital",1980-05-18,41.662635,-83.384718,0,55.955609,96.084283,13.039119
268,2019-08-07 00:13:37,4474324669797121,"fraud_Herman, Treutel and Dickens",misc_net,1133.81,M,37.7773,-119.0825,633,Health service manager,1927-09-09,37.120130,-119.565088,0,65.718782,135.939318,7.857118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111062,2019-04-15 14:22:37,2229378226512508,fraud_Corwin-Romaguera,travel,490.78,M,43.4987,-90.2796,1360,Occupational hygienist,1984-11-06,43.993807,-90.768963,0,92.249028,84.749079,4.702481
1111122,2020-02-21 03:48:30,342351256941125,fraud_Herzog Ltd,misc_pos,465.19,F,33.1194,-83.8235,3343,Theatre manager,1990-06-08,32.920528,-83.668336,0,85.679681,125.956938,3.013016
1111206,2020-02-17 19:26:03,4935858973307492,fraud_Bednar Inc,travel,580.51,M,32.8088,-83.1740,1841,Film/video editor,1975-06-01,33.498140,-82.353512,0,95.033243,89.334379,5.434378
1111292,2020-12-04 17:27:57,4562827002127,fraud_Mayert Group,shopping_pos,542.64,M,40.0987,-84.6342,22930,Media planner,1971-11-26,40.430829,-85.065994,0,60.933029,116.339029,4.140545
1111431,2019-01-02 07:04:23,3517527805128735,fraud_Bednar Group,misc_net,785.98,F,41.1573,-88.0619,1617,Medical secretary,1990-04-25,40.242491,-88.113635,0,56.089428,125.073033,5.835715

# 이상지출 탐지하기 2
-

In [13]:
train.groupby(['cc_num', 'category'])['amt'].agg(['mean', 'std'])

                                         mean         std
cc_num              category
60416207185         entertainment   49.701795   74.608322
                    food_dining     24.534795   39.018895
                    gas_transport   58.655615   15.538478
                    grocery_net     53.128049   16.442581
                    grocery_pos    100.907632   22.343677
...                                       ...         ...
4992346398065154184 misc_pos        69.220244  179.015499
                    personal_care   50.634531   51.923743
                    shopping_net   107.676667  256.882857
                    shopping_pos    67.826887  178.352765
                    travel          74.408286  557.313352

[13081 rows x 2 columns]

In [14]:
amt_by_category = train.groupby(['cc_num', 'category'])['amt'].agg(['mean', 'std'])
amt_by_category

                                         mean         std
cc_num              category
60416207185         entertainment   49.701795   74.608322
                    food_dining     24.534795   39.018895
                    gas_transport   58.655615   15.538478
                    grocery_net     53.128049   16.442581
                    grocery_pos    100.907632   22.343677
...                                       ...         ...
4992346398065154184 misc_pos        69.220244  179.015499
                    personal_care   50.634531   51.923743
                    shopping_net   107.676667  256.882857
                    shopping_pos    67.826887  178.352765
                    travel          74.408286  557.313352

[13081 rows x 2 columns]

In [15]:
train = pd.merge(train, amt_by_category, how='left', on=['cc_num', 'category'])
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,mean_x,std_x,amt_z_score,mean_y,std_y
0,2019-12-08 14:27:05,4292902571056973207,"fraud_Turner, Ruecker and Parisian",misc_pos,36.38,M,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,46.500378,-113.166539,0,68.647641,65.068697,-0.495901,139.712577,75.181756
1,2019-06-20 00:44:00,5152054598359927,"fraud_Lockman, West and Runte",grocery_pos,36.45,M,29.8872,-90.0331,55581,Biomedical scientist,1972-09-12,30.229110,-89.380019,0,61.405718,157.527222,-0.158422,62.851095,27.767980
2,2020-05-12 01:26:40,3547574373318979,"fraud_Huel, Hammes and Witting",grocery_pos,123.05,M,39.0319,-88.4074,2092,"Psychologist, clinical",1962-04-30,38.558958,-88.122956,0,63.552445,111.500902,0.533606,128.163857,19.248878
3,2020-06-21 03:37:16,213157767990030,fraud_Wisozk and Sons,misc_pos,151.77,F,41.6060,-109.2300,27971,Music therapist,1984-08-01,42.121831,-109.861563,0,95.250834,152.024640,0.371776,70.181310,88.310229
4,2020-08-19 05:20:56,4426075337087318654,"fraud_Herman, Treutel and Dickens",misc_net,1.75,M,39.0645,-95.6413,163415,Clinical cytogeneticist,1975-06-25,38.269669,-95.651064,0,58.805353,97.932683,-0.582598,34.980000,103.344470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2019-01-02 07:04:23,3517527805128735,fraud_Bednar Group,misc_net,785.98,F,41.1573,-88.0619,1617,Medical secretary,1990-04-25,40.242491,-88.113635,0,56.089428,125.073033,5.835715,78.412769,170.666173
1111432,2019-09-15 23:15:47,36485887555770,fraud_Shields-Wunsch,health_fitness,1.57,M,40.4971,-82.8342,267,Facilities manager,2005-01-29,41.349713,-82.224897,0,70.520312,73.261695,-0.941151,50.324228,62.725817
1111433,2020-09-14 22:42:04,38947654498698,"fraud_Herman, Treutel and Dickens",misc_net,314.33,F,39.3543,-82.5030,321,"Copywriter, advertising",1979-06-24,38.636519,-83.206128,0,53.651696,109.722256,2.375802,74.480333,160.704000
1111434,2020-05-03 23:14:48,4189814094741,fraud_Schumm PLC,health_fitness,1.17,M,33.7367,-86.1619,4159,Educational psychologist,1998-02-03,33.290748,-86.806002,0,57.839833,154.121481,-0.367696,57.814500,48.061131
1111435,2019-12-28 22:26:35,2269768987945882,"fraud_Hettinger, McCullough and Fay",home,33.23,F,42.6835,-77.8664,4895,Acupuncturist,1958-10-29,42.558121,-78.691432,0,65.545907,101.467606,-0.318485,61.790159,48.123883

In [16]:
train['category_z_score'] = (train['amt'] - train['mean_y']) / train['std_y']
train.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,mean_x,std_x,amt_z_score,mean_y,std_y,category_z_score
0,2019-12-08 14:27:05,4292902571056973207,"fraud_Turner, Ruecker and Parisian",misc_pos,36.38,M,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,46.500378,-113.166539,0,68.647641,65.068697,-0.495901,139.712577,75.181756,-1.374437
1,2019-06-20 00:44:00,5152054598359927,"fraud_Lockman, West and Runte",grocery_pos,36.45,M,29.8872,-90.0331,55581,Biomedical scientist,1972-09-12,30.229110,-89.380019,0,61.405718,157.527222,-0.158422,62.851095,27.767980,-0.950775
2,2020-05-12 01:26:40,3547574373318979,"fraud_Huel, Hammes and Witting",grocery_pos,123.05,M,39.0319,-88.4074,2092,"Psychologist, clinical",1962-04-30,38.558958,-88.122956,0,63.552445,111.500902,0.533606,128.163857,19.248878,-0.265670
3,2020-06-21 03:37:16,213157767990030,fraud_Wisozk and Sons,misc_pos,151.77,F,41.6060,-109.2300,27971,Music therapist,1984-08-01,42.121831,-109.861563,0,95.250834,152.024640,0.371776,70.181310,88.310229,0.923887
4,2020-08-19 05:20:56,4426075337087318654,"fraud_Herman, Treutel and Dickens",misc_net,1.75,M,39.0645,-95.6413,163415,Clinical cytogeneticist,1975-06-25,38.269669,-95.651064,0,58.805353,97.932683,-0.582598,34.980000,103.344470,-0.321546

In [17]:
train = train.drop(['mean_x','std_x','mean_y','std_y'], axis=1)
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,amt_z_score,category_z_score
0,2019-12-08 14:27:05,4292902571056973207,"fraud_Turner, Ruecker and Parisian",misc_pos,36.38,M,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,46.500378,-113.166539,0,-0.495901,-1.374437
1,2019-06-20 00:44:00,5152054598359927,"fraud_Lockman, West and Runte",grocery_pos,36.45,M,29.8872,-90.0331,55581,Biomedical scientist,1972-09-12,30.229110,-89.380019,0,-0.158422,-0.950775
2,2020-05-12 01:26:40,3547574373318979,"fraud_Huel, Hammes and Witting",grocery_pos,123.05,M,39.0319,-88.4074,2092,"Psychologist, clinical",1962-04-30,38.558958,-88.122956,0,0.533606,-0.265670
3,2020-06-21 03:37:16,213157767990030,fraud_Wisozk and Sons,misc_pos,151.77,F,41.6060,-109.2300,27971,Music therapist,1984-08-01,42.121831,-109.861563,0,0.371776,0.923887
4,2020-08-19 05:20:56,4426075337087318654,"fraud_Herman, Treutel and Dickens",misc_net,1.75,M,39.0645,-95.6413,163415,Clinical cytogeneticist,1975-06-25,38.269669,-95.651064,0,-0.582598,-0.321546
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2019-01-02 07:04:23,3517527805128735,fraud_Bednar Group,misc_net,785.98,F,41.1573,-88.0619,1617,Medical secretary,1990-04-25,40.242491,-88.113635,0,5.835715,4.145914
1111432,2019-09-15 23:15:47,36485887555770,fraud_Shields-Wunsch,health_fitness,1.57,M,40.4971,-82.8342,267,Facilities manager,2005-01-29,41.349713,-82.224897,0,-0.941151,-0.777259
1111433,2020-09-14 22:42:04,38947654498698,"fraud_Herman, Treutel and Dickens",misc_net,314.33,F,39.3543,-82.5030,321,"Copywriter, advertising",1979-06-24,38.636519,-83.206128,0,2.375802,1.492493
1111434,2020-05-03 23:14:48,4189814094741,fraud_Schumm PLC,health_fitness,1.17,M,33.7367,-86.1619,4159,Educational psychologist,1998-02-03,33.290748,-86.806002,0,-0.367696,-1.178593
1111435,2019-12-28 22:26:35,2269768987945882,"fraud_Hettinger, McCullough and Fay",home,33.23,F,42.6835,-77.8664,4895,Acupuncturist,1958-10-29,42.558121,-78.691432,0,-0.318485,-0.593472

In [18]:
happen_fraud = train.groupby(['merchant', 'category'])[['is_fraud']].mean().sort_values(by = 'is_fraud', ascending = False)
happen_fraud

                                                    is_fraud
merchant                             category
fraud_Herman, Treutel and Dickens    misc_net       0.025755
fraud_Kozey-Boehm                    shopping_net   0.023708
fraud_Boyer-Reichert                 shopping_net   0.023214
fraud_Schmeler, Bashirian and Price  shopping_net   0.022340
fraud_Kerluke-Abshire                shopping_net   0.021546
...                                                      ...
fraud_Schmidt-Larkin                 home           0.000000
fraud_Kunze, Larkin and Mayert       travel         0.000000
fraud_Schaefer, Fay and Hilll        entertainment  0.000000
fraud_Champlin, Rolfson and Connelly travel         0.000000
fraud_Kuphal-Toy                     food_dining    0.000000

[700 rows x 1 columns]

In [19]:
happen_fraud = happen_fraud.reset_index()

In [20]:
happen_fraud.columns = ['merchant', 'category', 'is_fraud_rate']

In [21]:
train = pd.merge(train, happen_fraud, how = 'left', on = ['merchant', 'category'])
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,amt_z_score,category_z_score,is_fraud_rate
0,2019-12-08 14:27:05,4292902571056973207,"fraud_Turner, Ruecker and Parisian",misc_pos,36.38,M,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,46.500378,-113.166539,0,-0.495901,-1.374437,0.003693
1,2019-06-20 00:44:00,5152054598359927,"fraud_Lockman, West and Runte",grocery_pos,36.45,M,29.8872,-90.0331,55581,Biomedical scientist,1972-09-12,30.229110,-89.380019,0,-0.158422,-0.950775,0.015285
2,2020-05-12 01:26:40,3547574373318979,"fraud_Huel, Hammes and Witting",grocery_pos,123.05,M,39.0319,-88.4074,2092,"Psychologist, clinical",1962-04-30,38.558958,-88.122956,0,0.533606,-0.265670,0.012512
3,2020-06-21 03:37:16,213157767990030,fraud_Wisozk and Sons,misc_pos,151.77,F,41.6060,-109.2300,27971,Music therapist,1984-08-01,42.121831,-109.861563,0,0.371776,0.923887,0.005140
4,2020-08-19 05:20:56,4426075337087318654,"fraud_Herman, Treutel and Dickens",misc_net,1.75,M,39.0645,-95.6413,163415,Clinical cytogeneticist,1975-06-25,38.269669,-95.651064,0,-0.582598,-0.321546,0.025755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2019-01-02 07:04:23,3517527805128735,fraud_Bednar Group,misc_net,785.98,F,41.1573,-88.0619,1617,Medical secretary,1990-04-25,40.242491,-88.113635,0,5.835715,4.145914,0.016334
1111432,2019-09-15 23:15:47,36485887555770,fraud_Shields-Wunsch,health_fitness,1.57,M,40.4971,-82.8342,267,Facilities manager,2005-01-29,41.349713,-82.224897,0,-0.941151,-0.777259,0.002647
1111433,2020-09-14 22:42:04,38947654498698,"fraud_Herman, Treutel and Dickens",misc_net,314.33,F,39.3543,-82.5030,321,"Copywriter, advertising",1979-06-24,38.636519,-83.206128,0,2.375802,1.492493,0.025755
1111434,2020-05-03 23:14:48,4189814094741,fraud_Schumm PLC,health_fitness,1.17,M,33.7367,-86.1619,4159,Educational psychologist,1998-02-03,33.290748,-86.806002,0,-0.367696,-1.178593,0.000691
1111435,2019-12-28 22:26:35,2269768987945882,"fraud_Hettinger, McCullough and Fay",home,33.23,F,42.6835,-77.8664,4895,Acupuncturist,1958-10-29,42.558121,-78.691432,0,-0.318485,-0.593472,0.002397

In [22]:
train.groupby('city_pop')['is_fraud'].value_counts()

city_pop  is_fraud
23        0           1793
          1              3
37        0            882
          1              4
43        0           1769
                      ...
2383912   1              4
2504700   0           1765
          1              4
2906700   0           3493
          1             23
Name: count, Length: 1691, dtype: int64

In [23]:
train[train['job'] == 'Dancer']

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,amt_z_score,category_z_score,is_fraud_rate
93849,2019-12-30 03:33:14,4629125581019,fraud_Cartwright-Harris,grocery_pos,281.48,F,35.1730,-84.6544,4870,Dancer,1957-04-15,34.383758,-85.354913,1,-1.076958,-0.707107,0.009981
170161,2019-07-13 03:46:16,501894933032,fraud_Padberg-Welch,grocery_pos,273.91,F,40.7547,-73.9925,1577385,Dancer,1949-02-15,39.919048,-73.215262,1,-0.935181,-0.707107,0.013619
211862,2019-12-29 23:13:29,4629125581019,fraud_Boyer PLC,shopping_net,885.44,F,35.1730,-84.6544,4870,Dancer,1957-04-15,35.313976,-83.907091,1,0.385686,-1.013655,0.020371
247705,2019-12-29 23:57:39,4629125581019,"fraud_Herman, Treutel and Dickens",misc_net,812.12,F,35.1730,-84.6544,4870,Dancer,1957-04-15,35.927193,-83.688705,1,0.208123,NaN,0.025755
443629,2019-12-30 16:22:51,4629125581019,fraud_Auer-West,shopping_net,1155.44,F,35.1730,-84.6544,4870,Dancer,1957-04-15,34.573302,-84.241912,1,1.039561,0.985762,0.017699
643684,2019-12-29 22:57:27,4629125581019,"fraud_Reichert, Shanahan and Hayes",shopping_net,1026.09,F,35.1730,-84.6544,4870,Dancer,1957-04-15,35.864776,-84.102899,1,0.726307,0.027893,0.011034
710441,2019-07-14 22:59:06,501894933032,fraud_Mayert Group,shopping_pos,965.23,F,40.7547,-73.9925,1577385,Dancer,1949-02-15,40.859356,-74.973340,1,0.779948,-0.707107,0.006941
745137,2019-07-13 23:41:41,501894933032,fraud_Mayert Group,shopping_pos,1031.80,F,40.7547,-73.9925,1577385,Dancer,1949-02-15,39.878139,-74.153618,1,0.945104,0.707107,0.006941
808043,2019-12-29 11:03:12,4629125581019,fraud_VonRueden Group,grocery_net,11.29,F,35.1730,-84.6544,4870,Dancer,1957-04-15,35.498311,-85.387971,1,-1.731293,NaN,0.006570
888869,2019-12-29 23:40:18,4629125581019,fraud_Kihn Inc,shopping_pos,989.25,F,35.1730,-84.6544,4870,Dancer,1957-04-15,35.840826,-85.487097,1,0.637089,-0.707107,0.005519
1044353,2019-12-30 22:38:52,4629125581019,fraud_Hermann and Sons,shopping_pos,1058.76,F,35.1730,-84.6544,4870,Dancer,1957-04-15,34.317471,-84.926969,1,0.805425,0.707107,0.007673
1075618,2019-07-14 01:50:39,501894933032,fraud_Kuhic Inc,grocery_pos,332.48,F,40.7547,-73.9925,1577385,Dancer,1949-02-15,40.241909,-73.257319,1,-0.789871,0.707107,0.012894
1110177,2019-12-30 02:14:55,4629125581019,fraud_Hackett-Lueilwitz,grocery_pos,315.76,F,35.1730,-84.6544,4870,Dancer,1957-04-15,34.402110,-84.799389,1,-0.993940,0.707107,0.013538

In [24]:
train['age'] = train['dob'].apply(lambda x : 2020-int(x[:4]))
train.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,dob,merch_lat,merch_long,is_fraud,amt_z_score,category_z_score,is_fraud_rate,age
0,2019-12-08 14:27:05,4292902571056973207,"fraud_Turner, Ruecker and Parisian",misc_pos,36.38,M,45.8433,-113.8748,218,"Therapist, horticultural",1995-08-16,46.500378,-113.166539,0,-0.495901,-1.374437,0.003693,25
1,2019-06-20 00:44:00,5152054598359927,"fraud_Lockman, West and Runte",grocery_pos,36.45,M,29.8872,-90.0331,55581,Biomedical scientist,1972-09-12,30.229110,-89.380019,0,-0.158422,-0.950775,0.015285,48
2,2020-05-12 01:26:40,3547574373318979,"fraud_Huel, Hammes and Witting",grocery_pos,123.05,M,39.0319,-88.4074,2092,"Psychologist, clinical",1962-04-30,38.558958,-88.122956,0,0.533606,-0.265670,0.012512,58
3,2020-06-21 03:37:16,213157767990030,fraud_Wisozk and Sons,misc_pos,151.77,F,41.6060,-109.2300,27971,Music therapist,1984-08-01,42.121831,-109.861563,0,0.371776,0.923887,0.005140,36
4,2020-08-19 05:20:56,4426075337087318654,"fraud_Herman, Treutel and Dickens",misc_net,1.75,M,39.0645,-95.6413,163415,Clinical cytogeneticist,1975-06-25,38.269669,-95.651064,0,-0.582598,-0.321546,0.025755,45

# 위도 경도 정보로 거리 계산하기
- 카드 사용자의 주거지 위치와 카드 사용처의 거리를 계산해 너무 멀면 사기일 가능성이 높다

In [25]:
# !pip install geopy

In [26]:
import geopy.distance

In [27]:
train['customer_coord'] = pd.Series(zip(train['lat'], train['long']))
train['merchant_coord'] = pd.Series(zip(train['merch_lat'], train['merch_long']))

In [28]:
train['distance'] = train.apply(lambda x : geopy.distance.distance(x['customer_coord'], x['merchant_coord']).km, axis = 1)
train.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,...,merch_lat,merch_long,is_fraud,amt_z_score,category_z_score,is_fraud_rate,age,customer_coord,merchant_coord,distance
0,2019-12-08 14:27:05,4292902571056973207,"fraud_Turner, Ruecker and Parisian",misc_pos,36.38,M,45.8433,-113.8748,218,"Therapist, horticultural",...,46.500378,-113.166539,0,-0.495901,-1.374437,0.003693,25,"(45.8433, -113.8748)","(46.500378000000005, -113.166539)",91.245470
1,2019-06-20 00:44:00,5152054598359927,"fraud_Lockman, West and Runte",grocery_pos,36.45,M,29.8872,-90.0331,55581,Biomedical scientist,...,30.229110,-89.380019,0,-0.158422,-0.950775,0.015285,48,"(29.8872, -90.0331)","(30.22911, -89.38001899999999)",73.502172
2,2020-05-12 01:26:40,3547574373318979,"fraud_Huel, Hammes and Witting",grocery_pos,123.05,M,39.0319,-88.4074,2092,"Psychologist, clinical",...,38.558958,-88.122956,0,0.533606,-0.265670,0.012512,58,"(39.0319, -88.4074)","(38.558958, -88.122956)",58.026673
3,2020-06-21 03:37:16,213157767990030,fraud_Wisozk and Sons,misc_pos,151.77,F,41.6060,-109.2300,27971,Music therapist,...,42.121831,-109.861563,0,0.371776,0.923887,0.005140,36,"(41.606, -109.23)","(42.121831, -109.861563)",77.666656
4,2020-08-19 05:20:56,4426075337087318654,"fraud_Herman, Treutel and Dickens",misc_net,1.75,M,39.0645,-95.6413,163415,Clinical cytogeneticist,...,38.269669,-95.651064,0,-0.582598,-0.321546,0.025755,45,"(39.0645, -95.6413)","(38.269669, -95.651064)",88.237598

In [29]:
spend_by_distance = train.groupby('cc_num')['distance'].agg(['mean', 'std']).reset_index()
spend_by_distance

                  cc_num       mean        std
0            60416207185  73.931890  28.986008
1            60422928733  78.980372  29.759039
2            60423098130  77.841088  27.978655
3            60427851591  76.338474  28.560318
4            60487002085  79.535516  28.901098
..                   ...        ...        ...
994  4958589671582726883  77.370036  29.295533
995  4973530368125489546  78.518799  29.821392
996  4980323467523543940  71.636674  27.757569
997  4989847570577635369  77.270222  30.006962
998  4992346398065154184  74.527948  29.139622

[999 rows x 3 columns]

In [30]:
train = pd.merge(train, spend_by_distance, how = 'left', on = 'cc_num')
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,...,is_fraud,amt_z_score,category_z_score,is_fraud_rate,age,customer_coord,merchant_coord,distance,mean,std
0,2019-12-08 14:27:05,4292902571056973207,"fraud_Turner, Ruecker and Parisian",misc_pos,36.38,M,45.8433,-113.8748,218,"Therapist, horticultural",...,0,-0.495901,-1.374437,0.003693,25,"(45.8433, -113.8748)","(46.500378000000005, -113.166539)",91.245470,73.737176,29.105642
1,2019-06-20 00:44:00,5152054598359927,"fraud_Lockman, West and Runte",grocery_pos,36.45,M,29.8872,-90.0331,55581,Biomedical scientist,...,0,-0.158422,-0.950775,0.015285,48,"(29.8872, -90.0331)","(30.22911, -89.38001899999999)",73.502172,79.640891,29.710334
2,2020-05-12 01:26:40,3547574373318979,"fraud_Huel, Hammes and Witting",grocery_pos,123.05,M,39.0319,-88.4074,2092,"Psychologist, clinical",...,0,0.533606,-0.265670,0.012512,58,"(39.0319, -88.4074)","(38.558958, -88.122956)",58.026673,74.860887,29.344143
3,2020-06-21 03:37:16,213157767990030,fraud_Wisozk and Sons,misc_pos,151.77,F,41.6060,-109.2300,27971,Music therapist,...,0,0.371776,0.923887,0.005140,36,"(41.606, -109.23)","(42.121831, -109.861563)",77.666656,76.415514,28.940491
4,2020-08-19 05:20:56,4426075337087318654,"fraud_Herman, Treutel and Dickens",misc_net,1.75,M,39.0645,-95.6413,163415,Clinical cytogeneticist,...,0,-0.582598,-0.321546,0.025755,45,"(39.0645, -95.6413)","(38.269669, -95.651064)",88.237598,74.991868,29.852552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2019-01-02 07:04:23,3517527805128735,fraud_Bednar Group,misc_net,785.98,F,41.1573,-88.0619,1617,Medical secretary,...,0,5.835715,4.145914,0.016334,30,"(41.1573, -88.0619)","(40.242491, -88.113635)",101.681861,75.726142,28.964331
1111432,2019-09-15 23:15:47,36485887555770,fraud_Shields-Wunsch,health_fitness,1.57,M,40.4971,-82.8342,267,Facilities manager,...,0,-0.941151,-0.777259,0.002647,15,"(40.4971, -82.8342)","(41.349713, -82.224897)",107.699093,75.390915,28.839943
1111433,2020-09-14 22:42:04,38947654498698,"fraud_Herman, Treutel and Dickens",misc_net,314.33,F,39.3543,-82.5030,321,"Copywriter, advertising",...,0,2.375802,1.492493,0.025755,41,"(39.3543, -82.50299999999999)","(38.636519, -83.206128)",100.299233,75.275089,29.222303
1111434,2020-05-03 23:14:48,4189814094741,fraud_Schumm PLC,health_fitness,1.17,M,33.7367,-86.1619,4159,Educational psychologist,...,0,-0.367696,-1.178593,0.000691,22,"(33.7367, -86.1619)","(33.290748, -86.806002)",77.637198,79.376243,30.729711
1111435,2019-12-28 22:26:35,2269768987945882,"fraud_Hettinger, McCullough and Fay",home,33.23,F,42.6835,-77.8664,4895,Acupuncturist,...,0,-0.318485,-0.593472,0.002397,62,"(42.6835, -77.8664)","(42.558121, -78.69143199999999)",69.103905,75.800535,28.439673

In [31]:
train['distance_z_score'] = (train['distance'] - train['mean']) / train['std']
train.head()

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,...,amt_z_score,category_z_score,is_fraud_rate,age,customer_coord,merchant_coord,distance,mean,std,distance_z_score
0,2019-12-08 14:27:05,4292902571056973207,"fraud_Turner, Ruecker and Parisian",misc_pos,36.38,M,45.8433,-113.8748,218,"Therapist, horticultural",...,-0.495901,-1.374437,0.003693,25,"(45.8433, -113.8748)","(46.500378000000005, -113.166539)",91.245470,73.737176,29.105642,0.601543
1,2019-06-20 00:44:00,5152054598359927,"fraud_Lockman, West and Runte",grocery_pos,36.45,M,29.8872,-90.0331,55581,Biomedical scientist,...,-0.158422,-0.950775,0.015285,48,"(29.8872, -90.0331)","(30.22911, -89.38001899999999)",73.502172,79.640891,29.710334,-0.206619
2,2020-05-12 01:26:40,3547574373318979,"fraud_Huel, Hammes and Witting",grocery_pos,123.05,M,39.0319,-88.4074,2092,"Psychologist, clinical",...,0.533606,-0.265670,0.012512,58,"(39.0319, -88.4074)","(38.558958, -88.122956)",58.026673,74.860887,29.344143,-0.573682
3,2020-06-21 03:37:16,213157767990030,fraud_Wisozk and Sons,misc_pos,151.77,F,41.6060,-109.2300,27971,Music therapist,...,0.371776,0.923887,0.005140,36,"(41.606, -109.23)","(42.121831, -109.861563)",77.666656,76.415514,28.940491,0.043232
4,2020-08-19 05:20:56,4426075337087318654,"fraud_Herman, Treutel and Dickens",misc_net,1.75,M,39.0645,-95.6413,163415,Clinical cytogeneticist,...,-0.582598,-0.321546,0.025755,45,"(39.0645, -95.6413)","(38.269669, -95.651064)",88.237598,74.991868,29.852552,0.443705

In [32]:
train = train.drop(['mean', 'std'], axis = 1)
train

,trans_date_trans_time,cc_num,merchant,category,amt,gender,lat,long,city_pop,job,...,merch_long,is_fraud,amt_z_score,category_z_score,is_fraud_rate,age,customer_coord,merchant_coord,distance,distance_z_score
0,2019-12-08 14:27:05,4292902571056973207,"fraud_Turner, Ruecker and Parisian",misc_pos,36.38,M,45.8433,-113.8748,218,"Therapist, horticultural",...,-113.166539,0,-0.495901,-1.374437,0.003693,25,"(45.8433, -113.8748)","(46.500378000000005, -113.166539)",91.245470,0.601543
1,2019-06-20 00:44:00,5152054598359927,"fraud_Lockman, West and Runte",grocery_pos,36.45,M,29.8872,-90.0331,55581,Biomedical scientist,...,-89.380019,0,-0.158422,-0.950775,0.015285,48,"(29.8872, -90.0331)","(30.22911, -89.38001899999999)",73.502172,-0.206619
2,2020-05-12 01:26:40,3547574373318979,"fraud_Huel, Hammes and Witting",grocery_pos,123.05,M,39.0319,-88.4074,2092,"Psychologist, clinical",...,-88.122956,0,0.533606,-0.265670,0.012512,58,"(39.0319, -88.4074)","(38.558958, -88.122956)",58.026673,-0.573682
3,2020-06-21 03:37:16,213157767990030,fraud_Wisozk and Sons,misc_pos,151.77,F,41.6060,-109.2300,27971,Music therapist,...,-109.861563,0,0.371776,0.923887,0.005140,36,"(41.606, -109.23)","(42.121831, -109.861563)",77.666656,0.043232
4,2020-08-19 05:20:56,4426075337087318654,"fraud_Herman, Treutel and Dickens",misc_net,1.75,M,39.0645,-95.6413,163415,Clinical cytogeneticist,...,-95.651064,0,-0.582598,-0.321546,0.025755,45,"(39.0645, -95.6413)","(38.269669, -95.651064)",88.237598,0.443705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111431,2019-01-02 07:04:23,3517527805128735,fraud_Bednar Group,misc_net,785.98,F,41.1573,-88.0619,1617,Medical secretary,...,-88.113635,0,5.835715,4.145914,0.016334,30,"(41.1573, -88.0619)","(40.242491, -88.113635)",101.681861,0.896127
1111432,2019-09-15 23:15:47,36485887555770,fraud_Shields-Wunsch,health_fitness,1.57,M,40.4971,-82.8342,267,Facilities manager,...,-82.224897,0,-0.941151,-0.777259,0.002647,15,"(40.4971, -82.8342)","(41.349713, -82.224897)",107.699093,1.120258
1111433,2020-09-14 22:42:04,38947654498698,"fraud_Herman, Treutel and Dickens",misc_net,314.33,F,39.3543,-82.5030,321,"Copywriter, advertising",...,-83.206128,0,2.375802,1.492493,0.025755,41,"(39.3543, -82.50299999999999)","(38.636519, -83.206128)",100.299233,0.856337
1111434,2020-05-03 23:14:48,4189814094741,fraud_Schumm PLC,health_fitness,1.17,M,33.7367,-86.1619,4159,Educational psychologist,...,-86.806002,0,-0.367696,-1.178593,0.000691,22,"(33.7367, -86.1619)","(33.290748, -86.806002)",77.637198,-0.056592
1111435,2019-12-28 22:26:35,2269768987945882,"fraud_Hettinger, McCullough and Fay",home,33.23,F,42.6835,-77.8664,4895,Acupuncturist,...,-78.691432,0,-0.318485,-0.593472,0.002397,62,"(42.6835, -77.8664)","(42.558121, -78.69143199999999)",69.103905,-0.235468

In [33]:
train = train[['gender', 'age', 'amt', 'amt_z_score', 'category_z_score', 'is_fraud_rate', 'distance_z_score', 'is_fraud']]

In [54]:
train = train.dropna()

In [55]:
X = train.drop('is_fraud', axis = 1)
y = train['is_fraud']

In [56]:
X = pd.get_dummies(X, drop_first = True)
X

,age,amt,amt_z_score,category_z_score,is_fraud_rate,distance_z_score,gender_M
0,25,36.38,-0.495901,-1.374437,0.003693,0.601543,True
1,48,36.45,-0.158422,-0.950775,0.015285,-0.206619,True
2,58,123.05,0.533606,-0.265670,0.012512,-0.573682,True
3,36,151.77,0.371776,0.923887,0.005140,0.043232,False
4,45,1.75,-0.582598,-0.321546,0.025755,0.443705,True
...,...,...,...,...,...,...,...
1111431,30,785.98,5.835715,4.145914,0.016334,0.896127,False
1111432,15,1.57,-0.941151,-0.777259,0.002647,1.120258,True
1111433,41,314.33,2.375802,1.492493,0.025755,0.856337,False
1111434,22,1.17,-0.367696,-1.178593,0.000691,-0.056592,True
1111435,62,33.23,-0.318485,-0.593472,0.002397,-0.235468,False

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, stratify = y, test_size = 0.4, random_state = 7)

In [59]:
from sklearn.preprocessing import RobustScaler

In [60]:
rs = RobustScaler()
scaled_X = rs.fit_transform(X_train)
scaled_X = pd.DataFrame(scaled_X, columns = X_train.columns)
scaled_X_valid = rs.fit_transform(X_valid)
scaled_X_valid = pd.DataFrame(scaled_X_valid, columns = X_train.columns)

In [49]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, roc_auc_score

In [51]:
xgb = XGBClassifier(max_depth = 5, n_estimators = 500, n_jobs = 10, random_state = 7)
xgb.fit(scaled_X, y_train)
valid_pred = xgb.predict(scaled_X_valid)
print(classification_report(y_valid, valid_pred))
print(roc_auc_score(y_valid, valid_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    442259
           1       0.74      0.56      0.64      2316

    accuracy                           1.00    444575
   macro avg       0.87      0.78      0.82    444575
weighted avg       1.00      1.00      1.00    444575

0.780787306792356

## 데이터 증폭하기

In [61]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1111208 entries, 0 to 1111435
Data columns (total 7 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   age               1111208 non-null  int64
 1   amt               1111208 non-null  float64
 2   amt_z_score       1111208 non-null  float64
 3   category_z_score  1111208 non-null  float64
 4   is_fraud_rate     1111208 non-null  float64
 5   distance_z_score  1111208 non-null  float64
 6   gender_M          1111208 non-null  bool
dtypes: bool(1), float64(5), int64(1)
memory usage: 60.4 MB

In [62]:
from imblearn.over_sampling import SMOTE

In [65]:
sm = SMOTE(random_state = 7)
X_smt, y_smt = sm.fit_resample(scaled_X, y_train)

In [66]:
y_smt.value_counts()

is_fraud
0    663386
1    663386
Name: count, dtype: int64

In [67]:
xgb_sm = XGBClassifier(max_depth = 5, n_estimators = 500, n_jobs = 10, random_state = 7)
xgb_sm.fit(X_smt, y_smt)
valid_pred_sm = xgb_sm.predict(scaled_X_valid)
print(classification_report(y_valid, valid_pred_sm))
print(roc_auc_score(y_valid, valid_pred_sm))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00    442258
           1       0.34      0.82      0.48      2226

    accuracy                           0.99    444484
   macro avg       0.67      0.91      0.74    444484
weighted avg       1.00      0.99      0.99    444484

0.9052475567299962

In [68]:
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import make_pipeline as imb_make_pipeline
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier

C:\Users\5-08\miniforge3\envs\fintech\lib\site-packages\dask\dataframe\__init__.py:42: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

In [75]:
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline

In [69]:
models = dict(XGB = XGBClassifier(n_jobs = 10, random_state = 7),
             RFC = RandomForestClassifier(n_jobs = 10, random_state = 7),
             LGBM = LGBMClassifier(n_jobs = 10, random_state = 7))
models

{'XGB': XGBClassifier(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, device=None, early_stopping_rounds=None,
               enable_categorical=False, eval_metric=None, feature_types=None,
               gamma=None, grow_policy=None, importance_type=None,
               interaction_constraints=None, learning_rate=None, max_bin=None,
               max_cat_threshold=None, max_cat_to_onehot=None,
               max_delta_step=None, max_depth=None, max_leaves=None,
               min_child_weight=None, missing=nan, monotone_constraints=None,
               multi_strategy=None, n_estimators=None, n_jobs=10,
               num_parallel_tree=None, random_state=7, ...),
 'RFC': RandomForestClassifier(n_jobs=10, random_state=7),
 'LGBM': LGBMClassifier(n_jobs=10, random_state=7)}

In [73]:
params = {
    'XGB' : {
        'xgbclassifier__max_depth' : [3, 5, 7],
        'xgbclassifier__n_estimators' : [100, 300, 500],
        'xgbclassifier__subsample' : [0.6, 0.8 ,1.0]
    },
    'RFC' : {
        'randomforestclassifier__max_depth' : [3, 5, 7],
        'randomforestclassifier__n_estimators' : [100, 300, 500]
    },
    'LGBM' : {
        'lgbmclassifier__max_depth' : [3, 5, 7],
        'lgbmclassifier__n_estimators' : [100, 300, 500],
        'lgbmclassifier__subsample' : [0.6, 0.8 ,1.0]
    }
}

In [74]:
# 각 모델별로 최적의 파라미터 찾고 성능 평가
best_estimators = {}
roc_auc_scores = {}
classfication_reports = {}

In [76]:
skf = StratifiedKFold(n_splits = 5, random_state = 10, shuffle = True)

In [77]:
for model_name, model in models.items() :
    print(model_name, model)
    pipe = Pipeline(model)
    rand_cv = RandomizedSearchCV(pipe, param_distributions = params[model_name], cv = skf, scoring = 'roc_auc', n_jobs = 10)
    rand_cv.fit(X_smt, y_smt)
    print('best parameters : ', rand_cv.best_params_)
    best_model = rand_cv.best_estimator_
    best_pred = best_model.predict(X_valid)
    print(classfication_reports(y_valid, best_pred))
    print(roc_auc_score(y_valid, best_pred))

XGB XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=10,
              num_parallel_tree=None, random_state=7, ...)

TypeError: 'XGBClassifier' object is not subscriptable